### ISSUE TITLE
Unable to open two instances of Mabioned

### ISSUE THREAD

**Issue by jiaaluo** [exectails/Mabioned#10]
This needed for region comparisons.
Refer to
https://github.com/exectails/Mabioned/issues/7
https://github.com/Aahzmandius/Mabioned/commit/0441348ee316d5d7550125f494cad812cf521491

**Comment by exectails** [comment]
In version 0.8.0a you can open multiple instances after disabling the "Single Instance" option in the settings.

![](https://i.imgur.com/XVs19cL.png)

**Comment by jiaaluo** [comment]
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mabioned.FrmMain.AddProp(Prop prop)
   at Mabioned.FrmMain.PasteSelectedEntity()
   at Mabioned.FrmMain.FrmMain_KeyUp(Object sender, KeyEventArgs e)
   at System.Windows.Forms.Control.OnKeyUp(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Form.ProcessKeyPreview(Message& m)
   at System.Windows.Forms.Control.ProcessKeyPreview(Message& m)
   at System.Windows.Forms.Control.ProcessKeyPreview(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

This just crash for me.

**Comment by jiaaluo** [comment]
Update on this issue, you must have set data folder first in order for to work.

**Comment by exectails** [comment]
Thanks for the report, I'll look into fixing this for the next version.
